dashscope_config:
  api_key: "sk-ws-H.PLELEYH.XZrN.MEQCIAG5WyT2SKrtP-NVO6zBhzkDPtgR4cro457ZUpIx4mrkAiAJ7QBvUjNxyuY-ob97Jx7AIdgUlmMtWrLUuRZuUISmJw"
  base_http_api_url: "https://dashscope.aliyuncs.com/api/v1"
